// flow-typed signature: b5de221ce060f4a67100a3b0b0038461
// flow-typed version: <<STUB>>/inferno-create-element_v3.6.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inferno-create-element'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'inferno-create-element' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inferno-create-element/dist/index.es' {
  declare module.exports: any;
}

declare module 'inferno-create-element/dist/index' {
  declare module.exports: any;
}

declare module 'inferno-create-element/dist/inferno-create-element' {
  declare module.exports: any;
}

declare module 'inferno-create-element/dist/inferno-create-element.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inferno-create-element/dist/index.es.js' {
  declare module.exports: $Exports<'inferno-create-element/dist/index.es'>;
}
declare module 'inferno-create-element/dist/index.js' {
  declare module.exports: $Exports<'inferno-create-element/dist/index'>;
}
declare module 'inferno-create-element/dist/inferno-create-element.js' {
  declare module.exports: $Exports<'inferno-create-element/dist/inferno-create-element'>;
}
declare module 'inferno-create-element/dist/inferno-create-element.min.js' {
  declare module.exports: $Exports<'inferno-create-element/dist/inferno-create-element.min'>;
}
declare module 'inferno-create-element/index' {
  declare module.exports: $Exports<'inferno-create-element'>;
}
declare module 'inferno-create-element/index.js' {
  declare module.exports: $Exports<'inferno-create-element'>;
}
