// flow-typed signature: 8871b2ac916d23f447463080f9c23ec8
// flow-typed version: <<STUB>>/inferno-component_v3.6.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'inferno-component'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'inferno-component' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'inferno-component/dist/index.es' {
  declare module.exports: any;
}

declare module 'inferno-component/dist/index' {
  declare module.exports: any;
}

declare module 'inferno-component/dist/inferno-component' {
  declare module.exports: any;
}

declare module 'inferno-component/dist/inferno-component.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'inferno-component/dist/index.es.js' {
  declare module.exports: $Exports<'inferno-component/dist/index.es'>;
}
declare module 'inferno-component/dist/index.js' {
  declare module.exports: $Exports<'inferno-component/dist/index'>;
}
declare module 'inferno-component/dist/inferno-component.js' {
  declare module.exports: $Exports<'inferno-component/dist/inferno-component'>;
}
declare module 'inferno-component/dist/inferno-component.min.js' {
  declare module.exports: $Exports<'inferno-component/dist/inferno-component.min'>;
}
declare module 'inferno-component/index' {
  declare module.exports: $Exports<'inferno-component'>;
}
declare module 'inferno-component/index.js' {
  declare module.exports: $Exports<'inferno-component'>;
}
